from desafio_iafront.jobs.graphics.scale_analysis.job_histogram_analysis import histogram_scale_analysis
from desafio_iafront.jobs.graphics.scale_analysis.job_scatter_analysis import scatter_scale_analysis
from desafio_iafront.jobs.graphics.job_compare_conversao import plot_conversao
from desafio_iafront.jobs.graphics.job_plot_conversao_particionada import analise_conversao_temporal